dist: trusty
language: node_js
node_js: lts/*
cache:
  bundler: true
  pip: true
  npm: true
before_install:
- pyenv local 3.6
install:
- travis_retry gem install s3_website -v 3.4.0
- travis_retry pip install awscli --upgrade --user
- travis_retry npm ci
- travis_retry cypress install
script:
- npm run build
# this is a quick hack to demo a branch build of a versioned file
# a real version of this would need to check if this ia branch or tag, and strip off
# any PT identifiers like what s3_deploy is doing
# also this is rebuilding all of the js files and it puts the pubic path in the js file
# so it might mean the non versioned file doesn't work anymore
- ASSET_PATH=branch/$TRAVIS_BRANCH/ npm run build
- npm run test:coverage -- --runInBand
- npm run start &
- wait-on http://localhost:8080
- $(npm bin)/cypress run --config video=false
after_script:
- ./s3_deploy.sh
