name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build_test:
    name: Build and Run Jest Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run Tests
        run: npm run test:coverage -- --runInBand
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          flags: jest
          token: ${{ secrets.CODECOV_TOKEN }}
  playwright:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        run: npx playwright test
        env:
          CI: "true"
      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v5
        with:
          flags: playwright
          token: ${{ secrets.CODECOV_TOKEN }}
          files: test-results/coverage/coverage.lcov
      - uses: concord-consortium/s3-deploy-action/deploy-path@v1
        if: always()
        id: s3-deploy-path
      - uses: aws-actions/configure-aws-credentials@v4
        if: always()
        with:
          role-to-assume: arn:aws:iam::612297603577:role/starter-projects
          aws-region: us-east-1
      - name: Upload Playwright Report
        if: always()
        run: aws s3 sync ./playwright-report s3://models-resources/starter-projects/playwright-report/${{ steps.s3-deploy-path.outputs.deployPath }} --delete --cache-control "no-cache, max-age=0"
      - uses: daun/playwright-report-summary@v3
        if: always()
        with:
          report-file: test-results/results.json
          report-url: https://models-resources.concord.org/starter-projects/playwright-report/${{ steps.s3-deploy-path.outputs.deployPath }}/
  s3-deploy:
    name: S3 Deploy
    needs:
      - build_test
      - playwright
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::612297603577:role/starter-projects
          aws-region: us-east-1
      - uses: concord-consortium/s3-deploy-action@v1
        id: s3-deploy
        with:
          bucket: models-resources
          prefix: starter-projects
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          deployRunUrl: https://models-resources.concord.org/starter-projects/__deployPath__/index.html
          # Parameters to GHActions have to be strings, so a regular yaml array cannot
          # be used. Instead the `|` turns the following lines into a string
          topBranches: |
            ["main"]
